### ISSUE TITLE
Android Build issue with ver2.51 - UE4 4.17.2

### ISSUE THREAD

**Issue by Yuka-Okabe** [Geromatic/Midi-Unreal#16]
Hi,
When I try building my project for Android with UE4 4.17.2, it doesn't work properly.  It looks like all MIDI Events are called at the same time just after it starts the MIDI Processor Component.

I also tried building the example project https://www.dropbox.com/s/gh5ym2uc3wprgia/Midi_Project.zip?dl=0 
both with UE4 4.16.3 and UE4 4.17.2 and the results are the below.

UE4 4.16.3 (Midi Asset ver.2.42)Android Development Build: Works(the cubes blink)
UE4 4.16.3 (Midi Asset ver.2.42)Android Shipping Build: Works(the cubes blink)
UE4 4.17.2 (Midi Asset ver.2.51)Android Development Build: Not Working（Nothing happen on the black screen）
UE4 4.17.2 (Midi Asset ver.2.51)Android Shipping Build: Not Working（Nothing happen on the black screen）

Is this a bug? 
As we faced a syncing problem with wave file and the MIDI file, we hope to try the newer version of your plugin. 
Thanks,

**Comment by Geromatic** [comment]
it might be the timing function.  I should call the platform clock.  I made a fix_android branch to fix that.

ill see if i can check if this fix works.

**Comment by Geromatic** [comment]
It was dealing with the timing function and I fixed the issue
