### ISSUE TITLE
In C++ example code FBufferReader is not a istream

### ISSUE THREAD

**Issue by AlexanderBaruta** [Geromatic/Midi-Unreal#21]
I'm on UE 4.22.3. 
I'm trying to read in a Midi from file using the example code as a starting point and using the provided example code:

FString path;
TArray<uint8> data;
bool result = FFileHelper::LoadFileToArray(data, path.GetCharArray().GetData());
FBufferReader reader((uint8*)data.GetData(), data.Num(), false);
MidiFile midi(reader);

fails to compile since FBufferReader is not a istream and MidiFile only accepts istreams in the file constructor.

**Comment by AlexanderBaruta** [comment]
This is part of a larger issue where MidiFile objects are not directly accessible to the user's C++ code because the MidiFile objects are not opened to the API so any attempt to use them directly will result in a Unresolved External error

**Comment by Geromatic** [comment]
updated readme file
