### ISSUE TITLE
MidiUtil::ticksToMs has long/int conversion problems

### ISSUE THREAD

**Issue by stani** [Geromatic/Midi-Unreal#3]
```
long k = MidiUtil::ticksToMs(122456L, 454545, 120);
UE_LOG(LogTemp, Warning, TEXT("%ld"), k);
```

result: -1440

**Comment by Geromatic** [comment]
time should always be unsigned.  

long ticksToMs(long ticks, int mpqn, int resolution) {
    return ((ticks \* (mpqn & 0x00000000ffffffffL)) / resolution) / 1000;
}

**Comment by stani** [comment]
Still something wrong with the new formula.

```
ticksToMs(9432,454545,120) -> 35727
ticksToMs(9452,454545,120) -> 11
```

> conversion may have fixed playback speed of midi.

`ticksToMs` is not used anywhere in the plugin, only `msToTicks` is used

**Comment by Geromatic** [comment]
seemed i confused myself with the other.  anyway I forced value to do a unsigned long long.  Seems like the multiplication is causing a value overflow

**Comment by stani** [comment]
Works good.
