### ISSUE TITLE
Seeking Platform Testers

### ISSUE THREAD

**Issue by Geromatic** [Geromatic/Midi-Unreal#6]
I am trying to get MIDI to work on all platforms that  Unreal supports. 

MIDI Interface [Input/Output] can only run on Linux, Window, Mac/IOS

if there are any bugs can you post the error log

**Comment by Whiiplash** [comment]
Hi,
I've already compiled this successfully on MacOS

**Comment by Geromatic** [comment]
Ya it successfully will compile for all main platforms now + Android/IOS.  The only issue was interacting with MIDI Input/Output devices.  Mac doesn't seem to have a built in MIDI Synth like Windows does, so I gotta figure out a way to code a Synth for the Mac/IOS build.
