### ISSUE TITLE
Using midi to trigger events for non-real-time capture

### ISSUE THREAD

**Issue by mattdw** [Geromatic/Midi-Unreal#7]
Hi,

I'm trying to render to (hi-res) video, using a midi file solely to drive level events. This project is making it all super-simple to wire things up (it's super clean, thanks!), but it seems to run in real-world time (I think) which is a bit awkward for my purposes, as my rendering is distinctly slower than realtime – I'd like to be able to use game elapsed time, or even to supply my own ticks into MidiProcessor::process.

Any interest in supporting this, or any thoughts on the best way for me to implement it?

Cheers,
Matt.

**Comment by Geromatic** [comment]
on the Midi component ...theres a play rate variable

It is a multiplier value 1 = default play speed

**Comment by mattdw** [comment]
Thanks, but that would be a simple multiplier, right? The problem I'm having is that each frame takes a variable and unknown length of time to actually render, so anything based on real-world time is going to go wrong.

Fine if there's no easy answer… I might just try a quick patch to see if GameState::ElapsedTime does what I need.

**Comment by Geromatic** [comment]
Hmm never worked with rendering videos

**Comment by mattdw** [comment]
Yeah, no problem! It gets a bit confusing with all the different timers involved! I'll see what I can dig up.

**Comment by Geromatic** [comment]
one way could be to store all the notes in a array in blueprint and enumerate through each item on each frame or time it takes to get to another note.

Trying to visualize the idea lol

**Comment by mattdw** [comment]
I've added a reference to UWorld to MidiProcessor, then used UWorld::TimeSeconds * 1000.0f as the "current time" getter, and now it worked perfectly for my purposes (I'm not actually outputting audio, just using midi to trigger events, although I'll take a look tomorrow at what the audio actually sounds like in game time.)

If you're interested, I'd be happy to expose this via a "use game time"/"use real time" toggle and write a cleaner patch than I currently have.

Thanks for your help!

**Comment by Geromatic** [comment]
I am interested.  It can be useful in certain situations

**Comment by Geromatic** [comment]
Added Game Time
